[Details]
Icon = "../../theme/icons/fyne.png"
Name = "TFLanHttpDesktop"
ID = "TFLanHttpDesktop.2025.0826"
Version = "0.0.1"
Build = 1

[Migrations]
fyneDo = true

[Source]
Repo = "https://github.com/mangenotwork/TFLanHttpDesktop"
Dir = "./"

[Development]
HelperText = "This binary was built with debug symbols"

[Release]
HelperText = "This binary was built without debug symbols"

[LinuxAndBSD]
GenericName = "TFLanHttpDesktop"
Categories = ["Development"]
Comment = "TFLanHttpDesktop About Transfer Files from LAN Http Desktop, 用于局域网内指定文件生成二维码或链接提供给三方设备用局域网http协议下载文件，三方设备也可以上传文件，桌面应用程序，跨平台"
Keywords = ["TFLanHttpDesktop", "fyne"]