[Details]
Icon = "icon.png"
Name = "TFLanHttpDesktop"
ID = "TFLanHttpDesktop.2025.0826"
Version = "0.4.1"
Build = 1

[Migrations]
fyneDo = true

[Source]
Repo = "https://github.com/mangenotwork/TFLanHttpDesktop"
Dir = "./"

[Development]
HelperText = "This binary was built with debug symbols"

[Release]
HelperText = "This binary was built without debug symbols"

[LinuxAndBSD]
GenericName = "TFLanHttpDesktop"
Categories = ["Development"]
Comment = "Transfer Files from LAN Http Desktop, 生成二维码或链接提供给局域网内的三方设备下载指定文件和上传文件，桌面应用程序，跨平台，绿色免安装"
Keywords = ["TFLanHttpDesktop", "fyne"]